services:
  iam-fetcher:
    build:
      context: .
      dockerfile: Dockerfile
      target: iam-fetcher
    volumes:
      - iam_token:/app/iam_token
    command: >
      /bin/sh -c 'python /app/fetch_iam_token.py'

  translate-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    depends_on:
      - iam-fetcher
    volumes:
      - iam_token:/app/iam_token
    ports:
      - "8080:8080"

  tester:
    build:
      context: .
      dockerfile: Dockerfile
      target: tester
    depends_on:
      - iam-fetcher
      - db
    environment:
      - YANDEX_IAM_TOKEN=${YANDEX_IAM_TOKEN}
    volumes:
      - iam_token:/app/iam_token

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  iam_token:
