services:
  translate-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - YANDEX_TRANSLATE_URL=https://translate.api.cloud.yandex.net/translate/v2/translate
    
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql