services:
  translate-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - IAM_TOKEN=t1.9euelZqRk5OQzpeSkZSSmYvIisnOx-3rnpWayc6JlZvJm5CWm5uVyp3Gis_l9PcJcxlK-e84bSfb3fT3SSEXSvnvOG0n283n9euelZrLzcqMmZOUjMebz5yQmpbGy-_8xeuelZrLzcqMmZOUjMebz5yQmpbGyw.dWLA0Udgz8LSg94MKi2ySOxEsK5wYZ4-ZKDs7hLho2lgwdF3oaAYnlo6oBcdfrIkREwwvcYEdKDfyMo8UR9ZAQ
      - FOLDER_ID=b1gtnk8rf36ddjmv1rc6
      - YANDEX_TRANSLATE_URL=https://translate.api.cloud.yandex.net/translate/v2/translate
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql